[build]
  base = "frontend"
  command = "npm ci && npm run build"
  functions = "../netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"

[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"