[build]
  base = "frontend"
  command = "npm install && npm run build"
  functions = "../netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"